services:
  nginx:
    image: nginx:latest
    container_name: meetly_nginx
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx:/etc/nginx/conf.d
      - ./laravel:/var/www/html
    depends_on:
      - laravel
      - fastapi

  laravel:
    build:
      context: ./laravel
      dockerfile: Dockerfile
    container_name: meetly_laravel
    volumes:
      - ./laravel:/var/www/html
    depends_on:
      - mysql
      - redis

  fastapi:
    build:
      context: ./fastapi
      dockerfile: Dockerfile
    container_name: meetly_fastapi
    volumes:
      - ./fastapi:/app
    environment:
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      DB_HOST: mysql
      REDIS_HOST: redis
    depends_on:
      - mysql
      - redis

  mysql:
    image: mysql:8
    container_name: meetly_mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql

  redis:
    image: redis:alpine
    container_name: meetly_redis
    ports:
      - "6379:6379"

volumes:
  mysql_data: