server {
    listen 80;
    server_name meetly.ru;
    return 301 https://$host$request_uri;
}

server {
    listen 443 ssl;
    server_name meetly.ru;

    ssl_certificate     /etc/nginx/conf.d/certs/meetly.crt;
    ssl_certificate_key /etc/nginx/conf.d/certs/meetly.key;

    root /var/www/html/public;
    index index.php;

    location / {
        try_files $uri $uri/ /index.php?$query_string;
    }

    location ~ \.php$ {
        try_files $uri =404;
        fastcgi_pass laravel:9000;
        include fastcgi_params;
        fastcgi_param SCRIPT_FILENAME $document_root$fastcgi_script_name;
    }
}